# Generated by Django 4.2 on 2023-06-17 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', 'init_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='plan_de_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='usuarios.plandevuelo'),
        ),
    ]
