# Generated by Django 4.2 on 2023-05-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('capacidad', models.IntegerField()),
                ('motor', models.CharField(max_length=50, verbose_name='Motor')),
                ('velocidad_crucero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanque_combustible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autonomia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='aeronaves', verbose_name='Imagen')),
            ],
        ),
    ]
