# Generated by Django 4.2 on 2023-05-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeadores_mdp', 'init_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planeadores_mdp.instructor')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planeadores_mdp.piloto')),
                ('planeador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planeadores_mdp.planeador')),
                ('remolcador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planeadores_mdp.remolcador')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
